import Link from 'next/link';
import type { RunSnapshot } from '@swarm/shared';
import snapshotJson from '@swarm/shared/fixtures/run-snapshot.json';
import { personaSections, reportSummary } from '../../../lib/report.ts';
import { personaEmoji, SEVERITY_COLOR } from '../../../lib/personaVisuals.ts';
import { Stars } from '../../../components/Stars.tsx';

// Epic 3 reads a converged run (C6). In Fake Swarm mode this is the seeded
// snapshot; with the real backend, fetch the run by id from InsForge instead —
// the report-shaping (lib/report.ts) and this markup are unchanged.
const snapshot = snapshotJson as unknown as RunSnapshot;

function screenOf(screenKey: string | null, edge: string): string {
  if (!screenKey) return edge;
  const parts = screenKey.split(':');
  return parts[2] ?? edge;
}

export default async function ReportPage({ params }: { params: Promise<{ runId: string }> }) {
  const { runId } = await params;
  const summary = reportSummary(snapshot);
  const sections = personaSections(snapshot);

  return (
    <div className="report">
      <header className="report__hero">
        <div className="report__crumb">
          <Link href="/" className="report__back">← Dashboard</Link>
          <span className="report__runid">run {runId}</span>
        </div>
        <h1>Beta-Test Report</h1>
        <p className="report__app">
          App-Under-Test: <b>{summary.appId}</b> · tested by a persona-diverse AI swarm before a single
          real user.
        </p>

        <div className="report__verdict">
          <div className="verdict__rating">
            <div className="verdict__num">{summary.swarmRating ?? '–'}<span>/5</span></div>
            <Stars value={summary.swarmRating ?? 0} size={22} />
            <div className="verdict__caption">Swarm Rating · {summary.personaCount} testers</div>
          </div>
          <div className="verdict__chips">
            <Chip value={summary.totalFindings} label="issues found" accent />
            <Chip value={summary.personaCount} label="personas" />
            <Chip value={`${summary.durationSec}s`} label="run time" />
          </div>
        </div>
      </header>

      <main className="report__sections">
        {sections.map(({ persona, findings }) => (
          <section key={persona.id} className="psection">
            <div className="psection__head">
              <span className="psection__emoji">{personaEmoji(persona.key)}</span>
              <div className="psection__id">
                <div className="psection__name">{persona.display_name}</div>
                <Stars value={persona.rating ?? 0} />
              </div>
              <div className="psection__count">
                {findings.length} {findings.length === 1 ? 'issue' : 'issues'}
              </div>
            </div>

            {persona.review_text && (
              <blockquote className="psection__review">“{persona.review_text}”</blockquote>
            )}

            {findings.length === 0 ? (
              <div className="psection__clean">✓ No issues — clean run for this persona.</div>
            ) : (
              <ul className="findings">
                {findings.map((f) => (
                  <li key={f.id} className="rfinding">
                    <span className="rfinding__sev" style={{ background: SEVERITY_COLOR[f.severity] }} />
                    <div className="rfinding__main">
                      <div className="rfinding__top">
                        <span className="rfinding__title">{f.title}</span>
                        <span className="rfinding__sevtag" style={{ color: SEVERITY_COLOR[f.severity] }}>
                          {f.severity}
                        </span>
                      </div>
                      <div className="rfinding__meta">
                        <span className="rfinding__edge">{f.edge_case}</span>
                        <span className="rfinding__screen">{screenOf(f.screen_key, f.edge_case)}</span>
                      </div>
                      <div className="rfinding__repro">{f.repro_steps}</div>
                    </div>
                    <div className="rfinding__shot" title={f.screenshot_url}>
                      <span>{screenOf(f.screen_key, f.edge_case)}</span>
                      <small>screenshot</small>
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </section>
        ))}
      </main>

      <footer className="report__footer">
        Shareable report · anyone with this link can view it. Generated by The AI Beta-Tester Swarm.
      </footer>
    </div>
  );
}

function Chip({ value, label, accent }: { value: number | string; label: string; accent?: boolean }) {
  return (
    <div className={`rchip ${accent ? 'rchip--accent' : ''}`}>
      <div className="rchip__value">{value}</div>
      <div className="rchip__label">{label}</div>
    </div>
  );
}
